### PR TITLE
Add approx guild count using another API

### PR DESCRIPTION
**Pull request by TejasLamba2006**

### CODE REVIEW

**Comment by TheGamer3514** [comment]
bad api, too much downtime. could cause more errors trying to call a down api

**Comment by TajuModding** [comment]
Are you sure about that?
image

**Comment by TheGamer3514** [comment]
thats pretty bad uptime for an api that would be called whenever someone uses the bot list

**Comment by TajuModding** [comment]
I would leave that to @ishaantek

**Comment by TheGamer3514** [comment]
also if the pull request was merged, you would get an error on startup. Do you even test your pull requests?

**Comment by TajuModding** [comment]
Why would I get an error?

Also know your place
image

**Comment by TheGamer3514** [comment]
most of your commits have been removed

**Comment by TajuModding** [comment]
No?

**Comment by TheGamer3514** [comment]
site ban was removed because it broke stuff.... 
thats most of your commits removed

**Comment by TajuModding** [comment]
Still this isnt a fighting showdown please let @ishaantek decide thanks

**Comment by TheGamer3514** [comment]
you started it

**Comment by TajuModding** [comment]
Kindly Check with these changes @ishaantek !

**Comment by apteryxxyz** [comment]
Please do **NOT** merge this pull request as the API's uptime of 91% over the past 30 days is below the acceptable standard of 99.99%. The lack of error handling to detect when the API is offline is concerning, as it will cause your website to break during the remaining 9% of the time. This translates to 3 days per month or 30 days per year, which is not acceptable.

Moreover, I have tested the API and it is not working at the moment.

**Comment by TajuModding** [comment]
@apteryxxyz 
Thank you for bringing this to our attention. We apologize for the inconvenience caused by the current downtime of our API. As you mentioned, we are in the process of switching to a new VPS, which is causing the temporary disruption of our services. We expect the API to be back up and running within an hour.

Regarding your concerns about error handling, we take the reliability of our API very seriously and have measures in place to monitor its uptime. Our team is constantly working to improve the reliability and performance of our services, and we appreciate your feedback.

**Comment by TajuModding** [comment]
We are pleased to inform you that our API is now back online, following the planned VPS migration. Our team has taken this opportunity to further polish and optimize the API for better performance and reliability. We have also implemented additional error handling mechanisms to ensure that any future downtime is minimized. Our commitment to providing high-quality services remains unwavering, and we are grateful for your patience during the brief disruption. As always, if you have any feedback or concerns, please do not hesitate to reach out to us.

**Comment by apteryxxyz** [comment]
@TajuModding you are mistaken, I was not commenting on the lack of "error handling" within your API, rather the lack of error handling within the changes of this pull request.

When your API is offline, the request that Universe List sends will throw an error (different from `data.error`), you have not added any method of catching that error, meaning the website will break.

Also, your API still has problems outside of the uptime:
- Some valid bot IDs result in an "Unknown Application", Dyno for example.
- When the inputted ID is not an application (and the API does produce a server error) the results `error` property is `false`. This means if someone was to use the bot info command on a user, the command will break, producing an error along the lines of `cannot read property 'bot' of undefined`.

The API is so inconsistent that with the same input, the result is sometimes different.
Sorry but it is not production ready.

**Comment by TajuModding** [comment]
Thank you for bringing these concerns to my attention, and I apologize for any confusion my previous response may have caused. I appreciate your feedback and would like to assure you that I am taking all necessary steps to address these issues.

Regarding the lack of error handling within the changes of the pull request, I understand that this is a critical aspect of ensuring the stability and reliability of the website. I will work to implement a method of catching errors that may occur when the API is offline, to prevent the website from breaking.

Additionally, I understand that there are still some inconsistencies and errors within the API itself, particularly with regards to valid bot IDs and the results they produce. I will investigate these issues further and work to resolve them as quickly as possible.

I appreciate your feedback and understand that these issues make the API less than ideal for production use at the moment. Rest assured that I am committed to improving the stability and reliability of our services, and I will continue to work diligently to address any issues that arise.

If you have any further concerns or feedback, please do not hesitate to reach out to me. Thank you again for bringing these concerns to my attention.

**Comment by TheGamer3514** [comment]
@ishaantek just close and lock this pull request

**Comment by LISplaysYT** [comment]
@TheGamer3514 why

**Comment by TheGamer3514** [comment]
Because all it does it break stuff even more

**Comment by ishaantek** [comment]
Thank you @TejasLamba2006 for your recent pull request. Unfortunately, the code does not currently meet the necessary requirements for merging into the repository.

Therefore, the pull request will be closed at this time. However, please know that I am willing to work with you to help resolve any issues and get your code merged.

I encourage you to submit a new pull request once the changes have been made and the code has been tested to ensure it is working properly. 

Best regards,
Ishaan Garg

**Comment by ishaantek** [comment]
Thank you @TejasLamba2006 for your recent pull request. Unfortunately, the code does not currently meet the necessary requirements for merging into the repository.

Therefore, the pull request will be closed at this time. However, please know that I am willing to work with you to help resolve any issues and get your code merged.

I encourage you to submit a new pull request once the changes have been made and the code has been tested to ensure it is working properly.

Best regards,
Ishaan Garg

**Pull request closed without merging**
