### PR TITLE
Added Status

### PR DESCRIPTION
**Pull request by Miya25**

### CODE REVIEW

**Comment by Miya25** [comment]
@ishaantek

**Comment by Miya25** [comment]
@ishaantek

**Comment by ishaantek** [comment]
Thank you for your pull request and feedback. Regarding the privacy policy, we do collect geolocation data for analytics purposes. As a result, we are unable to remove it from the privacy policy.

**Comment by Miya25** [comment]
uh what?

**Comment by Miya25** [comment]
ima just close it

**Pull request closed without merging**
