### PR TITLE
Added functionallity of bot kick when owner left

### PR DESCRIPTION
**Pull request by TejasLamba2006**

### CODE REVIEW

**Comment by TejasLamba2006** [comment]
Commits that can be ignored
- [e762c0e](https://github.com/ishaantek/UniverseList/pull/53/commits/e762c0e40d5c040caf9cd605f64d3983ee582181)
- [5365c2a](https://github.com/ishaantek/UniverseList/pull/53/commits/5365c2a924eecaa1953cd77e75f5fea2fac76eb9)
- [c672b54](https://github.com/ishaantek/UniverseList/pull/53/commits/c672b54024b8d656f5bda820f0ad36ef39b742b1)

**Comment by ishaantek** [comment]
Hello, what do you mean by ignoring the commits? If I merge this pull request, all the commits will be added.

**Comment by TejasLamba2006** [comment]
You can merge it safely. I have tested all changes and it shoudnt hamper anything

**Comment by ishaantek** [comment]
Thank you for your contribution to our project and for taking the time to create a pull request. However, after reviewing your changes, we have decided to decline this pull request as it appears to remove the package.json file, which is a critical file for our project.

We appreciate your efforts and welcome future contributions from you. In the meantime, we encourage you to review our project's guidelines and best practices to ensure that any future pull requests align with our project's standards.

Thank you again for your contribution, and we look forward to your future involvement in our project.

**Pull request merged**
