### PR TITLE
Formated Stuff also deleted package-lock.json

### PR DESCRIPTION
**Pull request by TejasLamba2006**
I have made some changes to the code formatting for better readability and consistency. This includes adjusting indentation, adding proper spacing, and using standardized naming conventions.

In addition, I have removed the `package-lock.json` file as it is not required for this project and can cause issues with version control.

Overall, these changes should improve the maintainability and clarity of the codebase. Please review the changes and let me know if there are any concerns or suggestions for improvement.

Thank you for your time and consideration. I look forward to working with you to continue improving this project.

### CODE REVIEW

**Comment by apteryxxyz** [comment]
The `package-lock.json` should be committed, especially when working with contributors. NPM themselves say to commit it.

https://docs.npmjs.com/cli/v6/configuring-npm/package-locks
> It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on.

**Comment by TejasLamba2006** [comment]
I see, adding `package-lock.json` back!

**Comment by TheGamer3514** [comment]
Also, most of the changes are not needed, pointless pull request

**Comment by ishaantek** [comment]
Thank you for your recent pull request. We appreciate your contribution and the time you took to create this pull request.

However, upon reviewing your changes, we have determined that the only modifications made were to the formatting of the code. While we appreciate your attention to detail, we do not consider these changes necessary for the functionality or maintenance of our project.

Therefore, we will not be merging this pull request. Nevertheless, we encourage you to continue contributing to our project in other ways.

**Pull request closed without merging**
